#!/bin/bash
dnf install -y httpd
chkconfig httpd on
service httpd start

# Generate a token to grab metadata
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`

# Fetch the Availability Zone from instance metadata using token
AZ=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/placement/availability-zone)

# Define the path to the index.html file
HTML_FILE="/var/www/html/index.html"

# Create the HTML content
cat > $HTML_FILE <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EC2 Instance Information</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f0f2f5; /* Light AWS-themed background */
            color: #16191f; /* Dark text for contrast */
            text-align: center;
        }
        .container {
            padding: 30px 40px;
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            border: 1px solid #e0e0e0;
        }
        h1 {
            color: #d86613; /* AWS Orange */
            margin-bottom: 20px;
        }
        p {
            font-size: 1.1em; /* Slightly larger for readability */
            line-height: 1.6;
        }
        strong {
            color: #232f3e; /* AWS Dark Blue/Grey */
            font-weight: bold;
        }
        .footer {
            margin-top: 25px;
            font-size: 0.9em;
            color: #5f6b7a;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>EC2 Instance Details</h1>
        <p>This instance is proudly serving from Availability Zone: <strong>$AZ</strong>.</p>
        <p class="footer"><em>This page was dynamically generated by a user data script at instance launch.</em></p>
    </div>
</body>
</html>
EOF